version: '3.1'
services:
  sksat-bot-discord:
    #build: .
    image: ghcr.io/sk2sat/sksat-bot-discord/sksat-bot-discord:master
    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
